### ISSUE TITLE
[リクエスト] （GH準拠の）ライセンスファイルを追加する

### ISSUE THREAD

**Issue by MarcoRavich** [T1210Taichi/Voice-Effects#1]
**[Google日本語]**
こんにちは。まず、この素晴らしい作品に感謝します！

[HyMPS プロジェクト](https://forart.it/HyMPS)（[オーディオ セクション](https://github.com/FORARTfe/HyMPS#-) \ [エフェクト ページ](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Effects.md#--) \ [ボーカル](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Effects.md#vocals-)）でこれを「公開」したので、GH 準拠のライセンス ファイルを追加していただけますか？

ご存知のとおり、ライセンス条件を明示することは、他のオープン プロジェクトでソース（だけでなく）を再利用/適応/変更する方法をより良く/より速く理解できるようにするために非常に重要です。その逆も同様です。

些細なことのように聞こえるかもしれませんが、ライセンス ファイルの省略により、関連するバッジの生成も一貫性が失われます。

![](https://badgen.net/github/license/T1210Taichi/Voice-Effects)
（バッジ ジェネレーターの URL: https://badgen.net/github/license/T1210Taichi/Voice-Effects)

GH のライセンス ウィザード ツールを使用すると、標準化されたバッジを簡単に設定できます。

最後に、リストされているプロジェクトの開発者間のコラボレーション（したがって進化）を促進するために、分類とリソースへのリンクをどのように改善できるか（ご意見）をお知らせください。

それが役に立つ/刺激になることを願っています！

**[ENG]**
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [AUDIO section](https://github.com/FORARTfe/HyMPS#- ) \ [Effects page](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Effects.md#-- ) \ [Vocals](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Effects.md#vocals-)), can you please add a GH-compliant license file for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/T1210Taichi/Voice-Effects)
(badge-generator URL: https://badgen.net/github/license/T1210Taichi/Voice-Effects)

You can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by MarcoRavich** [comment]
バンプ（リクエストが更新されました）。
Bump (request updated).

**Comment by T1210Taichi** [comment]
[Google English]

Hi! Thanks for using my work!

I've added the license file. Sorry if there are any mistakes, it's my first time doing this.

I wish your project every success.

[日本語]
こんにちは。この作品を利用してくれてありがとうございます！

ライセンスファイルを追加しました。
初めての経験なので不手際があれば申し訳ございません。

プロジェクトの成功を願っています。

**Comment by MarcoRavich** [comment]
[Google日本語]
こんにちは、今はうまくいきました。ありがとうございます！

すべてのオープンソース プロジェクトが成功することを祈っています！

[ENG]
Hi there, works now thanks !

I wish *all* open source projects every success !
